language: node_js
branches:
  only:
    - master
node_js:
    - "8"
install:
    - npm install
    - npm install npm@latest -g
    - npm ci
script:
    - npm run doc
    - npm run build
    - npm run test

env:
  global:
    - GH_REF: github.com/deep-js/doc.git
    - SECRET_VAR1=SECRET1
  matrix:
  - SECRET_VAR2=SECRET2

matrix:
  allow_failures:
    - env: SECRET_VAR1=SECRET1 SECRET_VAR2=SECRET2


