language: node_js

branches:
  only:
    - master
    
node_js:
    - "8"
    
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      
cache:
  directories:
    - ./node_modules
    
install:
  - npm install
  - npm install @compodoc/compodoc

script:
  - ng test
  - ng build --prod --aot
  - npm run doc
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  
env:
  global:
    - GH_REF: github.com/deep-js/doc.git

  




