language: node_js
branches:
  only:
    - master
node_js:
    - "8"
install:
  - npm install
  - npm install @compodoc/compodoc

script:
  - ng test
  - ng build --prod --aot
  - npm run doc
env:
  global:
    - GH_REF: github.com/deep-js/doc.git




