language: node_js

branches:
  only:
    - master

node_js:
    - "8"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


install:
  - npm install npm@latest -g
  - npm install coveralls
  - npm install @compodoc/compodoc

script:
  - ng build
  - npm run compodoc
  - bash ./deploy.sh

env:
  global:
    - GH_REF: github.com/deep-js/doc.git



